### ISSUE TITLE
Hello，Could you show the version of pynn and nest，thanks！

### ISSUE THREAD

**Issue by clancylea** [roberthangu/snn_object_recognition#1]

**Comment by roberthangu** [comment]
Hi, thanks for your message. Please try it with PyNN 0.8.1. In case that
breaks, try 0.8.0.

**Comment by clancylea** [comment]
Hi,i have a problem with this code,When I run with MPI, it doesn't run, and it stops here and doesn't continue running. If I don't use MPI, it will be fine.![](https://github.com/clancylea/pynq-sobel/blob/master/picture/EA1104B15710EDD645ED1D92B7791CAE.png)

**Comment by clancylea** [comment]
![ea1104b15710edd645ed1d92b7791cae](https://user-images.githubusercontent.com/42167380/53316725-e28bab00-3903-11e9-93e7-6e93cf104135.png)

**Comment by clancylea** [comment]
![tim 20190225134831](https://user-images.githubusercontent.com/42167380/53316790-1d8dde80-3904-11e9-855d-c339b107a3d3.jpg)

**Comment by roberthangu** [comment]
Closed due to inactivity.
